name: Bug report
description: Create a report to help us improve
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Application Logs
      description: Please copy the logs from the "Logs" tab in the app.
      render: text
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the tool are you using? (e.g. v1.1.4)
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Windows
        - macOS (Intel)
        - macOS (Apple Silicon)
    validations:
      required: true
